version: 0.2

phases:
  build:
    commands:
      - echo Building images via docker-compose...
      - docker-compose build
       #  Docker images are saved in a s3 bucket and later used in deployment.
      - docker save nidos-backend | gzip -c > nidos-backend.tar.gz
      - docker save nidos-frontend | gzip -c > nidos-frontend.tar.gz
      - docker save nidos-nginx | gzip -c > nidos-nginx.tar.gz
artifacts:
  files: # Artifacts that are copied to EC2 during deployment.
    - start-service.sh
    - stop-service.sh
    - docker-compose.yml
    - nidos-backend.tar.gz
    - nidos-frontend.tar.gz
    - nidos-nginx.tar.gz
    - appspec.yml
