# Local dev overrides
version: '3.7'

services:
  nidos-backend:
    build:
      context: ./
      target: development
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - ./interfaces:/usr/src/interfaces
      - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
  nidos-frontend:
    build:
      context: ./
      target: build
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - ./interfaces:/usr/src/interfaces
      - /usr/src/app/node_modules
    command: yarn dev
  nidos-nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
  nidos-db:
    container_name: nidos-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
