version: '3.7'

services:
  nidos-backend:
    container_name: nidos-backend
    image: nidos-backend
    command: yarn run start:dev
  nidos-frontend:
    container_name: nidos-frontend
    image: nidos-frontend
    command: yarn run start
