version: '3.5'
services:
  adminer:
    image: adminer
    ports:
      - '8080:8080'
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nidos
      POSTGRES_PASSWORD: password
