name: Nidos Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  ci_backend:
    runs-on: ubuntu-latest
    env:
      backend-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Build backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose build nidos-backend
      - name: Run backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose up -d nidos-backend
      - name: Audit backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose exec -T nidos-backend yarn audit
      - name: Test backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose exec -T nidos-backend yarn test
  # @TODO add ci_frontend job && linter step to ci_backend
