name: Nidos Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  ci_backend:
    runs-on: ubuntu-latest
    env:
      backend-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Build backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose build nidos-backend
      - name: Run backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose up -d nidos-backend
      - name: Audit backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose exec -T nidos-backend yarn audit
      - name: Test backend
        working-directory: ${{ env.backend-directory }}
        run: docker-compose exec -T nidos-backend yarn test
  ci_frontend:
    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Build frontend
        working-directory: ${{ env.frontend-directory }}
        run: docker-compose build nidos-frontend
      - name: Run frontend
        working-directory: ${{ env.frontend-directory }}
        run: docker-compose up -d nidos-frontend
      - name: Audit frontend
        working-directory: ${{ env.frontend-directory }}
        run: docker-compose exec -T nidos-frontend yarn audit
      - name: Test frontend
        working-directory: ${{ env.frontend-directory }}
        run: docker-compose exec -T nidos-frontend yarn test
      - name: Lint frontend
        working-directory: ${{ env.frontend-directory }}
        run: docker-compose exec -T nidos-frontend yarn lint
